### PR TITLE
Add default index option

### PR DESCRIPTION
**Pull request by alexcarpenter**
```vue
<Tabs :defaultIndex="1">
      ...
</Tabs>
```

### CODE REVIEW

**Comment by jakedohm** [comment]
Hey @alexcarpenter thanks for the PR! So I thought about doing this, but I'm undecided between your recommended API, and the following API, where you can add a default prop to a <Tab> component. I also need to validate that it's okay for a tab other than the first one to be initially active and look at how that works with screenreaders.

What do you think about this API v.s. a `defaultIndex `prop?

```vue
<Tabs>
  <TabList>
    <Tab>Give</Tab>
    <Tab default>You</Tab>
    <Tab>Up</Tab>
  </TabList>

  <TabPanels>
    ...
</Tabs>
```

**Comment by alexcarpenter** [comment]
@jakedohm Got it, this seemed to mimic the Reach implementation and the most straightforward setup since you are already defining the defaultIndex as 0 within the tabs component. I'm not to familiar with Vue and how you'd pass the data back up to the parent from the tab component. 

Feel free to close this out if you are leaning more towards the other API. It's been fun to get my eyes back onto some Vue code again. 👍

**Review by jakedohm — CHANGES_REQUESTED** [review]
This looks good. I think it would make more sense to set a default for the `defaultIndex` prop to `0` then to have an inline `or` statement. If you agree, then if you make that change, I'll merge!

**Comment by jakedohm** [comment]
@alexcarpenter I requested one "nitpick" change, but other than that, I like this API. I may re-consider for the Vue 3 version, but this is good for now 👍

**Comment by alexcarpenter** [comment]
@jakedohm great suggestion, updated 👍

**Review by jakedohm — APPROVED** [review]

**Pull request merged**
